# Generated by Django 6.0.4 on 2026-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(default='HQ', help_text='Department / Division mapping', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_adjust_physical_stock',
            field=models.BooleanField(default=False, help_text='Explicit permission to adjust warehouse stock'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff_Edit', 'Staff (Editor)'), ('Staff_View', 'Staff (Viewer)')], default='Staff_View', max_length=20),
        ),
    ]
