# Generated by Django 6.0.4 on 2026-08-12 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_product_warehouse_notification_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='allocated_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Planned', 'Planned'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=50),
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.batch')),
                ('production_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='core.productionrun')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='core.salesorder')),
            ],
        ),
    ]
