# Generated by Django 6.0.4 on 2026-08-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_product_warehouse_notification_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrylog',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material'),
        ),
        migrations.AddField(
            model_name='registrylog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
