# Generated by Django 6.0.4 on 2026-08-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_batch_allocated_quantity_alter_productionrun_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='material',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='external_origin',
            field=models.CharField(blank=True, help_text='For inbound from supplier', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='core.batch')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shipment')),
            ],
        ),
    ]
