# Generated by Django 6.0.4 on 2026-08-12 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_shipment_batch_remove_shipment_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Arrived', 'Arrived'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Preparing', max_length=50),
        ),
    ]
