# Generated by Django 6.0.4 on 2026-08-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shipment_acknowledged_by_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
