# Generated by Django 6.0.4 on 2026-08-12 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shipment_last_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discrepancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_discrepancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='discrepancy_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='has_discrepancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockallocation',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='core.shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Arrived', 'Arrived'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Discrepant', 'Discrepant (Shortage)')], default='Preparing', max_length=50),
        ),
    ]
