# Generated by Django 6.0.4 on 2026-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shipment_approved_by_shipment_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
