# Generated by Django 6.0.4 on 2026-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shipmentitem_date_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approval_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
