# Generated by Django 6.0.4 on 2026-08-16 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_purchaseorder_approval_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_sos', to=settings.AUTH_USER_MODEL),
        ),
    ]
