# Generated by Django 6.0.4 on 2026-08-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_purchaseorder_updated_at_purchaseorder_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='linked_production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pos', to='core.productionrun'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Pending Allocation', 'Pending Allocation'), ('Awaiting Materials', 'Awaiting Materials'), ('Planned', 'Planned'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=50),
        ),
    ]
