# Generated by Django 6.0.4 on 2026-08-16 05:43

from django.db import migrations


def copy_roles(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    Role = apps.get_model('core', 'Role')

    # Ensure standard roles exist
    standard_roles = ['Admin', 'Manager', 'Purchaser', 'Manufacturing', 'Warehouse', 'Staff_Edit', 'Staff_View']
    role_objects = {}
    for r in standard_roles:
        obj, created = Role.objects.get_or_create(name=r)
        role_objects[r] = obj

    for user in CustomUser.objects.all():
        if user.role:
            # Map the old string role to the new Role object
            if user.role in role_objects:
                user.roles.add(role_objects[user.role])
            else:
                obj, created = Role.objects.get_or_create(name=user.role)
                user.roles.add(obj)
                role_objects[user.role] = obj

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_allowed_locations_customuser_roles_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_roles),
    ]
