# Generated by Django 6.0.4 on 2026-08-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_copy_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='linked_production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_shipments', to='core.productionrun'),
        ),
    ]
