# Generated by Django 6.0.4 on 2026-08-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shipment_linked_production_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft (Manufacturing)'), ('Logistics Review', 'Logistics Review'), ('Pending Approval', 'Pending Approval'), ('Preparing', 'Approved / Preparing'), ('Dispatched', 'Dispatched'), ('Arrived', 'Arrived'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Discrepant', 'Discrepant (Shortage)')], default='Draft', max_length=50),
        ),
    ]
