# Generated by Django 6.0.4 on 2026-08-17 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
