# Generated by Django 6.0.4 on 2026-08-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shipment_assigned_to_shipment_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertimeline',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.shipment'),
        ),
    ]
