# Generated by Django 6.0.4 on 2026-08-17 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ordertimeline_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='exact_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='exact_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='fefo_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='signoff_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='supervisor_signoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RunMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wastage_reason', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='core.productionrun')),
            ],
        ),
    ]
