# Generated by Django 6.0.4 on 2026-08-18 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_batch_reserved_quantity_productionrun_exact_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordertimeline',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.productionrun'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft (Manufacturing)'), ('Logistics Review', 'Logistics Review'), ('Pending Approval', 'Pending Approval'), ('Preparing', 'Approved / Preparing'), ('Dispatched', 'Dispatched'), ('Arrived', 'Arrived'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Discrepant', 'Discrepant (Shortage)'), ('Cancelled', 'Cancelled / Scrapped')], default='Draft', max_length=50),
        ),
    ]
