# Generated by Django 6.0.4 on 2026-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_material_is_active_ordertimeline_production_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
