# Generated by Django 6.0.4 on 2026-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productionrun_actual_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client_address',
            field=models.TextField(blank=True, help_text='Destination address for outbound shipments', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client_contact',
            field=models.CharField(blank=True, help_text='Contact person and phone/email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='external_tracking_id',
            field=models.CharField(blank=True, help_text='Real logistics company tracking ID', max_length=255, null=True),
        ),
    ]
