# Generated by Django 6.0.4 on 2026-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_shipment_client_address_shipment_client_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.CharField(blank=True, help_text='Manual location entry', max_length=255, null=True),
        ),
    ]
