# Generated by Django 6.0.4 on 2026-08-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_batch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Facility', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.warehouse'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.CharField(blank=True, help_text='Zone/Aisle (Free Text)', max_length=255, null=True),
        ),
    ]
