# Generated by Django 6.0.4 on 2026-08-21 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_batch_warehouse_alter_batch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
