# Generated by Django 6.0.4 on 2026-08-21 07:24

from django.db import migrations, models
from django.db.models import F


def fold_reserved_into_allocated(apps, schema_editor):
    """
    reserved_quantity was a second, disconnected 'stock committed' counter that
    never got its release side wired up correctly. Fold any leftover value into
    allocated_quantity (the counter the rest of the app actually uses) before the
    field is dropped, so no in-flight holds are silently lost.
    """
    Batch = apps.get_model('core', 'Batch')
    Batch.objects.filter(reserved_quantity__gt=0).update(
        allocated_quantity=F('allocated_quantity') + F('reserved_quantity')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_productionrun_created_by'),
    ]

    operations = [
        migrations.RunPython(fold_reserved_into_allocated, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='batch',
            name='reserved_quantity',
        ),
    ]
