# Generated by Django 6.0.4 on 2026-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_batch_reserved_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertimeline',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
