# Generated by Django 6.0.4 on 2026-08-24 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_client_supplier_salesorder_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Pending', 'Pending (Approved)'), ('Awaiting Acknowledgement', 'Awaiting Manufacturing Acknowledgement'), ('In Production', 'In Production'), ('Ready to Ship', 'Ready to Ship'), ('Partially Shipped', 'Partially Shipped'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ShipmentItemReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.shipmentitem')),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
    ]
