# Generated by Django 6.0.4 on 2026-08-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_salesorder_status_shipmentitemreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client_contact_name',
            field=models.CharField(blank=True, help_text="Contact person's name", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client_contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone or email', max_length=100, null=True),
        ),
    ]
