# Generated by Django 6.0.4 on 2026-08-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_split_client_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='client_contact',
        ),
    ]
