# Generated by Django 6.0.4 on 2026-08-26 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_shipment_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrun',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Pending Allocation', 'Pending Allocation'), ('Awaiting Materials', 'Awaiting Materials'), ('Planned', 'Planned'), ('InProgress', 'In Progress'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductionRunYieldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('log_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_logs', to='core.productionrun')),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
            },
        ),
    ]
