# Generated by Django 6.0.4 on 2026-09-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_seed_so_at_risk_window_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseUtilizationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('used_mt', models.DecimalField(decimal_places=3, max_digits=14)),
                ('capacity_mt', models.DecimalField(decimal_places=3, max_digits=14)),
                ('utilization_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_snapshots', to='core.warehouse')),
            ],
            options={
                'ordering': ['-snapshot_date', 'warehouse_id'],
                'unique_together': {('warehouse', 'snapshot_date')},
            },
        ),
    ]
