# Generated by Django 6.0.4 on 2026-09-10 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_warehouseutilizationsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('status', models.CharField(choices=[('ok', 'Generated'), ('empty', 'No notable signals'), ('skipped', 'Skipped (disabled)'), ('error', 'Failed')], default='ok', max_length=10)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('signals_json', models.JSONField(blank=True, default=dict)),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('model_id', models.CharField(blank=True, max_length=80)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.ForeignKey(blank=True, help_text='The user who triggered a manual run; null for the scheduled job.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
