# Generated by Django 6.0.4 on 2026-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_seed_logistics_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='closed_date',
            field=models.DateField(blank=True, help_text='Date this batch stopped costing rent - fully consumed to zero, or spoiled/disposed. Null while the batch is still open (Active/Quarantined).', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='rental_rate_per_mt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Rate charged for this batch's rent (RM/MT/day), locked in at receipt (warehouse's rate at the time, or the PO line's negotiated override). Immune to later changes to Warehouse.rental_cost_per_mt.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='negotiated_rental_rate_per_mt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Custom negotiated rental rate (RM/MT/day) for batches received against this line. Leave blank to use the destination warehouse's standard rate at time of receipt.", max_digits=10, null=True),
        ),
    ]
