# Generated by Django 6.0.4 on 2026-09-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_rental_rate_live_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_mt_per_unit',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text="Weight in MT per unit, regardless of unit_of_measure's label", max_digits=10),
        ),
    ]
