# Generated by Django 6.0.4 on 2026-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_convert_materials_to_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='credited_to_so',
            field=models.BooleanField(default=False),
        ),
    ]
