# Generated by Django 6.0.4 on 2026-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_normalize_registrylog_quantity_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Logistics Review', 'Logistics Review'), ('Pending Approval', 'Pending Approval'), ('Preparing', 'Approved / Preparing'), ('Dispatched', 'Dispatched'), ('Arrived', 'Arrived'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Discrepant', 'Discrepant (Shortage)'), ('Cancelled', 'Cancelled / Scrapped')], default='Draft', max_length=50),
        ),
    ]
