# Generated by Django 6.0.4 on 2026-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_shipment_draft_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecipe',
            name='quantity_required',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
