# Generated by Django 6.0.4 on 2026-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_seed_qa_hold_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='location_type',
            field=models.CharField(choices=[('Storage', 'Storage'), ('Manufacturing', 'Manufacturing'), ('Both', 'Storage & Manufacturing')], max_length=50),
        ),
    ]
