# Generated by Django 6.0.4 on 2026-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_warehouse_storage_and_manufacturing'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseutilizationsnapshot',
            name='billing_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='warehouseutilizationsnapshot',
            name='daily_rent_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='warehouseutilizationsnapshot',
            name='quarantined_mt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='warehouseutilizationsnapshot',
            name='rent_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
