# Generated by Django 6.0.4 on 2026-09-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_seed_dss_saving_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Accepted', 'Accepted'), ('Dismissed', 'Dismissed')], db_index=True, max_length=10)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('move_mt', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate_per_mt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_daily_saving', models.DecimalField(decimal_places=2, max_digits=14)),
                ('est_total_saving', models.DecimalField(decimal_places=2, max_digits=14)),
                ('est_stay_days', models.PositiveIntegerField(default=0)),
                ('dismiss_reason', models.CharField(blank=True, choices=[('not_worth_it', 'Not worth the effort'), ('needed_here', 'Stock is needed where it is'), ('destination', "Destination isn't suitable"), ('other', 'Other')], max_length=20)),
                ('dismiss_note', models.CharField(blank=True, max_length=255)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_suggestions', to='core.batch')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_decisions', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_suggestions_to', to='core.warehouse')),
                ('origin_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_suggestions_from', to='core.warehouse')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_suggestions', to='core.shipment')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
    ]
