# Generated by Django 6.0.4 on 2026-09-21 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_seed_dss_snooze_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
