# Generated by Django 6.0.4 on 2026-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_runextramaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrylog',
            name='action_type',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Adjusted', 'Adjusted (Audit)'), ('Consumed_For_Manufacturing', 'Consumed For Manufacturing'), ('Produced', 'Produced'), ('Spoiled_Disposal', 'Spoiled / Disposed'), ('QA_Extension', 'Expiry Extended (QA)'), ('Draft_Transfer_Deleted', 'Draft Transfer Deleted')], max_length=50),
        ),
    ]
