# Generated by Django 6.0.4 on 2026-09-23 09:11

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_registrylog_draft_transfer_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='client_contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone or email', max_length=100, null=True, validators=[core.validators.validate_phone_or_email]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[core.validators.validate_phone]),
        ),
    ]
